// packages/shared/src/knowledge-base/brightway.ts
// BrightWay product data — as of April 2026

import type { CreditCard } from "../types/products.js";

export const BRIGHTWAY_CARDS: CreditCard[] = [
  {
    id: "brightway-standard",
    name: "BrightWay",
    issuer: "OneMain Financial",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: { regular: 35.99, type: "fixed", floor: 19.99 },
    annualFee: { min: 0, max: 89, waivable: false },
    cashBack: { enabled: true, baseRate: 1.0 },
    creditLimit: { startingMin: 300, startingMax: 1500, eventualMax: 15000 },
    fees: {
      foreignTransaction: 1.0,
      cashAdvance: "Greater of $10 or 3%",
      latePayment: "Up to $40",
    },
    features: [
      "No security deposit required",
      "Reports to all 3 credit bureaus",
      "Milestone reward system",
      "Mastercard global acceptance",
      "Invite-only — no application required",
    ],
    milestones: {
      paymentsPerMilestone: 6,
      rewards: [
        { type: "apr_decrease", description: "Reduce your APR (floor: 19.99%)" },
        { type: "credit_limit_increase", description: "Increase your credit limit (ceiling: $15,000)" },
      ],
      graduationMilestones: 4,
      graduationCard: "BrightWay+",
      forfeitOnLatePayment: true,
    },
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: true,
    website: "https://onemainfinancial.com/credit-cards/brightway",
    phone: "1-800-961-5577",
    dataAsOf: "2026-04",
  },
  {
    id: "brightway-cashback",
    name: "BrightWay 1.5% Cashback",
    issuer: "OneMain Financial",
    network: "Mastercard",
    targetMarket: "near-prime",
    apr: { regular: 29.99, type: "fixed", floor: 19.99 },
    annualFee: { min: 0, max: 49, waivable: false },
    cashBack: { enabled: true, baseRate: 1.5 },
    creditLimit: { startingMin: 500, startingMax: 3000, eventualMax: 15000 },
    fees: {
      foreignTransaction: 1.0,
      cashAdvance: "Greater of $10 or 3%",
      latePayment: "Up to $40",
    },
    features: [
      "1.5% cash back on all purchases",
      "No security deposit required",
      "Reports to all 3 credit bureaus",
      "Milestone reward system",
      "Mastercard global acceptance",
    ],
    milestones: {
      paymentsPerMilestone: 6,
      rewards: [
        { type: "apr_decrease", description: "Reduce your APR (floor: 19.99%)" },
        { type: "credit_limit_increase", description: "Increase your credit limit" },
      ],
      graduationMilestones: 4,
      graduationCard: "BrightWay+",
      forfeitOnLatePayment: true,
    },
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: true,
    website: "https://onemainfinancial.com/credit-cards/brightway",
    phone: "1-800-961-5577",
    dataAsOf: "2026-04",
  },
  {
    id: "brightway-plus",
    name: "BrightWay+",
    issuer: "OneMain Financial",
    network: "Mastercard",
    targetMarket: "near-prime",
    apr: { regular: 24.99, type: "fixed" },
    annualFee: { min: 0, max: 0, waivable: false },
    cashBack: { enabled: true, baseRate: 1.0 },
    creditLimit: { startingMin: 1000, startingMax: 3000, eventualMax: 15000 },
    fees: {
      foreignTransaction: 1.0,
      cashAdvance: "Greater of $10 or 3%",
      latePayment: "Up to $40",
    },
    features: [
      "$0 annual fee",
      "Graduation product from BrightWay after 4 milestones",
      "1% cash back on all purchases",
      "Reports to all 3 credit bureaus",
      "Mastercard global acceptance",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: true,
    website: "https://onemainfinancial.com/credit-cards/brightway",
    phone: "1-800-961-5577",
    dataAsOf: "2026-04",
  },
];
