// packages/shared/src/knowledge-base/competitors.ts
// Competitor card data — as of April 2026
// TODO (Dev 2 ELT-7): Verify/expand from sprint2-research.md

import type { CreditCard } from "../types/products.js";

export const COMPETITOR_CARDS: CreditCard[] = [
  {
    id: "capital-one-platinum-secured",
    name: "Capital One Platinum Secured",
    issuer: "Capital One",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: { regular: 29.99, type: "variable" },
    annualFee: { min: 0, max: 0, waivable: false },
    cashBack: { enabled: false, baseRate: 0 },
    creditLimit: { startingMin: 200, startingMax: 1000, eventualMax: 3000 },
    fees: { foreignTransaction: 0 },
    features: [
      "$0 annual fee",
      "Secured card — requires deposit",
      "Reports to all 3 credit bureaus",
      "Automatic credit line reviews",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: true,
    depositRequired: true,
    inviteOnly: false,
    website: "https://capitalone.com",
    dataAsOf: "2026-04",
  },
  {
    id: "indigo-platinum",
    name: "Indigo Platinum Mastercard",
    issuer: "Celtic Bank",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: { regular: 35.9, type: "fixed" },
    annualFee: { min: 0, max: 99, waivable: false },
    cashBack: { enabled: false, baseRate: 0 },
    creditLimit: { startingMin: 300, startingMax: 300, eventualMax: 300 },
    fees: { foreignTransaction: 1.0 },
    features: [
      "Pre-qualification available",
      "Reports to all 3 credit bureaus",
      "No security deposit",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "destiny-mastercard",
    name: "Destiny Mastercard",
    issuer: "First Electronic Bank",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: { regular: 35.9, type: "fixed" },
    annualFee: { min: 59, max: 99, waivable: false },
    cashBack: { enabled: false, baseRate: 0 },
    creditLimit: { startingMin: 300, startingMax: 700, eventualMax: 700 },
    fees: { foreignTransaction: 1.0 },
    features: [
      "Pre-qualification available",
      "Reports to all 3 credit bureaus",
      "No security deposit",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "credit-one-platinum",
    name: "Credit One Platinum Visa",
    issuer: "Credit One Bank",
    network: "Visa",
    targetMarket: "subprime",
    apr: { regular: 29.74, type: "variable" },
    annualFee: { min: 39, max: 99, waivable: false },
    cashBack: { enabled: true, baseRate: 1.0 },
    creditLimit: { startingMin: 300, startingMax: 1500, eventualMax: 5000 },
    fees: { foreignTransaction: 3.0 },
    features: [
      "1% cash back on eligible purchases",
      "Reports to all 3 credit bureaus",
      "Pre-qualification available",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "surge-platinum",
    name: "Surge Platinum Mastercard",
    issuer: "Continental Finance",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: { regular: 35.9, type: "fixed" },
    annualFee: { min: 75, max: 125, waivable: false },
    cashBack: { enabled: false, baseRate: 0 },
    creditLimit: { startingMin: 300, startingMax: 1000, eventualMax: 2000 },
    fees: { foreignTransaction: 3.0 },
    features: [
      "Reports to all 3 credit bureaus",
      "No security deposit",
      "Initial credit limit doubling option",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "aspire-cashback",
    name: "Aspire Cash Back Reward Card",
    issuer: "Metropolitan Commercial Bank",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: { regular: 29.99, type: "variable" },
    annualFee: { min: 49, max: 175, waivable: false },
    cashBack: { enabled: true, baseRate: 3.0 },
    creditLimit: { startingMin: 300, startingMax: 1000, eventualMax: 2000 },
    fees: { foreignTransaction: 3.0 },
    features: [
      "3% cash back on gas, groceries, utilities",
      "Reports to all 3 credit bureaus",
      "No security deposit",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "revvi-card",
    name: "Revvi Card",
    issuer: "Mill Creek Bank",
    network: "Visa",
    targetMarket: "subprime",
    apr: { regular: 35.99, type: "fixed" },
    annualFee: { min: 75, max: 99, waivable: false },
    cashBack: { enabled: true, baseRate: 1.0 },
    creditLimit: { startingMin: 300, startingMax: 300, eventualMax: 1000 },
    fees: { foreignTransaction: 3.0 },
    features: [
      "1% cash back rewards",
      "Reports to all 3 credit bureaus",
      "No security deposit",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "opensky-secured",
    name: "OpenSky Secured Visa",
    issuer: "Capital Bank",
    network: "Visa",
    targetMarket: "subprime",
    apr: { regular: 25.64, type: "variable" },
    annualFee: { min: 35, max: 35, waivable: false },
    cashBack: { enabled: false, baseRate: 0 },
    creditLimit: { startingMin: 200, startingMax: 3000, eventualMax: 3000 },
    fees: { foreignTransaction: 3.0 },
    features: [
      "No credit check required",
      "Reports to all 3 credit bureaus",
      "Secured — requires deposit",
      "Low annual fee for secured card",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: true,
    depositRequired: true,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
];
