import type { CreditCard } from "../types/products.js";

export const COMPETITOR_CARDS: CreditCard[] = [
  {
    id: "capital-one-platinum-secured",
    name: "Capital One Platinum Secured",
    issuer: "Capital One",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: {
      regular: 28.99,
      type: "variable",
    },
    annualFee: {
      min: 0,
      max: 0,
      waivable: false,
      note: "$0 annual fee",
    },
    cashBack: {
      enabled: false,
      baseRate: 0,
    },
    creditLimit: {
      startingMin: 200,
      startingMax: 1000,
      eventualMax: 3000,
    },
    fees: {
      foreignTransaction: 0,
      latePayment: "Up to $40",
    },
    features: [
      "No annual fee",
      "Refundable security deposit",
      "Automatic credit line review after 6 months",
      "Reports to all 3 credit bureaus",
      "No foreign transaction fee",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: true,
    depositRequired: true,
    depositRange: { min: 49, max: 200 },
    inviteOnly: false,
    website: "https://www.capitalone.com",
    dataAsOf: "2026-04",
  },
  {
    id: "indigo-platinum",
    name: "Indigo Platinum Mastercard",
    issuer: "Celtic Bank",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: {
      regular: 35.9,
      type: "fixed",
    },
    annualFee: {
      min: 0,
      max: 175,
      waivable: false,
      note: "$175 first year, $49 after; plus $12.50/month maintenance fee after year 1",
    },
    cashBack: {
      enabled: false,
      baseRate: 0,
    },
    creditLimit: {
      startingMin: 300,
      startingMax: 300,
      eventualMax: 300,
    },
    fees: {
      foreignTransaction: 1.0,
      latePayment: "Up to $40",
      monthly: "$12.50 after year 1",
    },
    features: [
      "Pre-qualification available",
      "No security deposit",
      "Reports to all 3 credit bureaus",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "destiny-mastercard",
    name: "Destiny Mastercard",
    issuer: "First Electronic Bank",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: {
      regular: 35.99,
      type: "fixed",
    },
    annualFee: {
      min: 75,
      max: 175,
      waivable: false,
      note: "Varies by offer; check terms",
    },
    cashBack: {
      enabled: true,
      baseRate: 1.5,
      note: "1.5% for targeted applicants only",
    },
    creditLimit: {
      startingMin: 500,
      startingMax: 700,
      eventualMax: 1500,
    },
    fees: {
      foreignTransaction: 1.0,
      latePayment: "Up to $40",
    },
    features: [
      "Pre-qualification available",
      "No security deposit",
      "Reports to all 3 credit bureaus",
      "1.5% cash back for eligible applicants",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "credit-one-platinum-visa",
    name: "Credit One Platinum Visa",
    issuer: "Credit One Bank",
    network: "Visa",
    targetMarket: "subprime",
    apr: {
      regular: 28.24,
      type: "variable",
    },
    annualFee: {
      min: 75,
      max: 99,
      waivable: false,
      note: "$75 first year, $99/year ($8.25/month) after",
    },
    cashBack: {
      enabled: true,
      baseRate: 1.0,
      categoryRates: [
        { category: "gas", rate: 1.0 },
        { category: "groceries", rate: 1.0 },
        { category: "utilities", rate: 1.0 },
      ],
      note: "1% cash back on gas, groceries, and utilities only",
    },
    creditLimit: {
      startingMin: 300,
      startingMax: 750,
      eventualMax: 2000,
    },
    fees: {
      foreignTransaction: 3.0,
      latePayment: "Up to $39",
    },
    features: [
      "Pre-qualification available",
      "No security deposit",
      "Reports to all 3 credit bureaus",
      "1% cash back on select categories",
      "Automatic credit limit review",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "surge-platinum-mastercard",
    name: "Surge Platinum Mastercard",
    issuer: "Continental Finance / Celtic Bank",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: {
      regular: 35.9,
      type: "fixed",
    },
    annualFee: {
      min: 75,
      max: 125,
      waivable: false,
      note: "Annual fee varies by offer; may also have monthly fee",
    },
    cashBack: {
      enabled: false,
      baseRate: 0,
    },
    creditLimit: {
      startingMin: 300,
      startingMax: 1000,
      eventualMax: 2000,
    },
    fees: {
      foreignTransaction: 3.0,
      latePayment: "Up to $40",
      monthly: "Up to $10/month on some offers",
    },
    features: [
      "No security deposit",
      "Credit limit increase possible after 6 months",
      "Reports to all 3 credit bureaus",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "aspire-cashback-rewards",
    name: "Aspire Cashback Rewards Card",
    issuer: "The Bank of Missouri",
    network: "Mastercard",
    targetMarket: "subprime",
    apr: {
      regular: 29.99,
      type: "variable",
    },
    annualFee: {
      min: 49,
      max: 175,
      waivable: false,
      note: "Annual fee varies; $49-$175 first year, $49 after",
    },
    cashBack: {
      enabled: true,
      baseRate: 1.0,
      categoryRates: [
        { category: "gas", rate: 3.0 },
        { category: "groceries", rate: 3.0 },
        { category: "utilities", rate: 3.0 },
      ],
      note: "3% on gas, groceries, utilities; 1% on all other purchases",
    },
    creditLimit: {
      startingMin: 350,
      startingMax: 1000,
      eventualMax: 2000,
    },
    fees: {
      foreignTransaction: 3.0,
      latePayment: "Up to $40",
    },
    features: [
      "3% cash back on gas, groceries, utilities",
      "No security deposit",
      "Reports to all 3 credit bureaus",
      "Pre-qualification available",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "revvi-visa",
    name: "Revvi Card (Visa)",
    issuer: "MRV Banks",
    network: "Visa",
    targetMarket: "subprime",
    apr: {
      regular: 35.99,
      type: "fixed",
    },
    annualFee: {
      min: 75,
      max: 75,
      waivable: false,
      note: "$75 first year, $48 after (billed monthly at $4/month)",
    },
    cashBack: {
      enabled: true,
      baseRate: 1.0,
      note: "1% cash back on Revvi card payments only (not purchases)",
    },
    creditLimit: {
      startingMin: 300,
      startingMax: 300,
      eventualMax: 1000,
    },
    fees: {
      foreignTransaction: 3.0,
      latePayment: "Up to $40",
      monthly: "$4/month after year 1",
    },
    features: [
      "No security deposit",
      "Reports to all 3 credit bureaus",
      "1% cash back on payments",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: false,
    depositRequired: false,
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
  {
    id: "opensky-secured-visa",
    name: "OpenSky Secured Visa",
    issuer: "Capital Bank",
    network: "Visa",
    targetMarket: "subprime",
    apr: {
      regular: 22.64,
      type: "variable",
    },
    annualFee: {
      min: 35,
      max: 35,
      waivable: false,
      note: "$35 annual fee",
    },
    cashBack: {
      enabled: false,
      baseRate: 0,
    },
    creditLimit: {
      startingMin: 200,
      startingMax: 3000,
      eventualMax: 3000,
    },
    fees: {
      foreignTransaction: 3.0,
      latePayment: "Up to $40",
    },
    features: [
      "No credit check required",
      "Lowest APR option for secured cards",
      "Reports to all 3 credit bureaus",
      "Low annual fee",
    ],
    bureauReporting: ["Equifax", "Experian", "TransUnion"],
    secured: true,
    depositRequired: true,
    depositRange: { min: 200, max: 3000 },
    inviteOnly: false,
    dataAsOf: "2026-04",
  },
];
